"""baseline_existing_schema

Revision ID: a04c9527bebf
Revises: 
Create Date: 2026-10-06 18:10:12.860443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a04c9527bebf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_chat_notebook_id'), table_name='chat_messages')
    op.create_index(op.f('ix_chat_messages_notebook_id'), 'chat_messages', ['notebook_id'], unique=False)
    op.drop_index(op.f('idx_notebooks_user_id'), table_name='notebooks')
    op.create_index(op.f('ix_notebooks_user_id'), 'notebooks', ['user_id'], unique=False)
    op.drop_index(op.f('idx_refresh_user_id'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.alter_column('sources', 'analysis',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_sources_notebook_id'), table_name='sources')
    op.create_index(op.f('ix_sources_notebook_id'), 'sources', ['notebook_id'], unique=False)
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_sources_notebook_id'), table_name='sources')
    op.create_index(op.f('idx_sources_notebook_id'), 'sources', ['notebook_id'], unique=False)
    op.alter_column('sources', 'analysis',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.create_index(op.f('idx_refresh_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.drop_index(op.f('ix_notebooks_user_id'), table_name='notebooks')
    op.create_index(op.f('idx_notebooks_user_id'), 'notebooks', ['user_id'], unique=False)
    op.drop_index(op.f('ix_chat_messages_notebook_id'), table_name='chat_messages')
    op.create_index(op.f('idx_chat_notebook_id'), 'chat_messages', ['notebook_id'], unique=False)
    # ### end Alembic commands ###
